version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
      POSTGRES_DB: portfolio
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - 5432:5432
  gradle:
    build:
      context: .
      dockerfile: ./docker/gradle/Dockerfile
    depends_on:
      - postgres
  maven:
    build:
      context: .
      dockerfile: ./docker/maven/Dockerfile
    depends_on:
      - postgres
