version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
      POSTGRES_DB: portfolio
      PGDATA: /data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - 5432:5432
