server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/portfolio"
    username: "portfolio"
    password: "portfolio"
  jpa:
    show-sql: true
    properties:
      dialect: "org.hibernate.dialect.PostgreSQLDialect"
    #drop n create table again, good for testing, comment this in production
    hibernate:
      ddl-auto: "create"
